name: Trigger Deploy

on:
  push:
    branches: [ master ]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger stock-concept-vue deploy
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT }}" \
            https://api.github.com/repos/zhouboyi1998/stock-concept-vue/dispatches \
            -d '{"event_type":"deploy"}'
